---
- name: Fedora post-installation playbook
  hosts: localhost
  tasks:
    - name: Update repositories
      ansible.builtin.dnf:
        name: "*"
        update_cache: yes
        state: latest
      become: true
    - name: Install packages
      ansible.builtin.dnf:
        name:
          - android-tools
          - firewalld
          - ftp
          - gh
          - gimp
          - git
          - gnome-boxes
          - gnome-shell-extension-gsconnect
          - gnucash
          - golang
          - inkscape
          - jetbrains-mono-fonts-all
          - jq
          - lua
          - neovim
          - nodejs
          - openvpn
          - pandoc
          - pipx
          - podman
          - podman-compose
          - python3-psutil
          - python3-sympy
          - ruby-devel
          - ruff
          - ripgrep
          - sqlite
          - stow
          - texlive-scheme-full
          - tmux
          - toolbox
          - vim
          - wl-clipboard
          - xq
        state: present
      become: true
    - name: Use stow to link dotfiles
      ansible.builtin.command:
        cmd: "stow --adopt --target='{{ ansible_env.HOME }}' --dir='{{ ansible_env.HOME }}/.local/share/dotfiles' --stow ."
    - name: Disable mouse acceleration
      ansible.builtin.dconf:
        key: /org/gnome/desktop/peripherals/mouse/accel-profile
        value: "'flat'"
        state: present
    - name: Enable firewall
      block:
        - name: Enable and start firewalld
          ansible.builtin.systemd:
            name: firewalld
            enabled: yes
            state: started
        - name: Enable firewalld in the home zone
          ansible.posix.firewalld:
            state: enabled
            immediate: yes
            permanent: yes
            zone: home
    - name: Install GitHub Copilot CLI extension
      ansible.builtin.command:
        cmd: "gh extension install github/gh-copilot"
    - block:
      - name: Install Golang tools
        set_fact:
          GOPATH: "{{ ansible_env.HOME }}/.local/share/go"
      - name: Install fabric framework
        ansible.builtin.command:
          cmd: "go install github.com/danielmiessler/fabric@latest"
