---
- name: Setup security tools
  hosts: localhost
  tasks:
    - name: Update repositories
      ansible.builtin.dnf:
        name: "*"
        update_cache: yes
        state: latest
      become: true
    - name: Install packages
      ansible.builtin.dnf:
        name:
          - aircrack-ng
          - binwalk
          - chisel
          - hashcat
          - hivex
          - hydra
          - medusa
          - nmap
          - radare2
          - tcpdump
          - whois
          - wireshark
        become: true
    - name: Golang security tools
      block:
        - name: Define GOPATH
          set_fact:
            GOPATH: "{{ ansible_env.HOME }}/.local/share/go"
        - name: Install ffuf
          ansible.builtin.command:
            cmd: "go install github.com/ffuf/ffuf/v2@latest"
        - name: Install httpx
          ansible.builtin.command:
            cmd: "go install github.com/projectdiscovery/httpx/cmd/httpx@latest" 
        - name: Install interactsh-client
          ansible.builtin.command:
            cmd: "go install -v github.com/projectdiscovery/interactsh/cmd/interactsh-client@latest"
    - name: Install caido
      ansible.builtin.command:
        cmd: "echo 'TEFURVNUX1JFTEVBU0U9IiQoY3VybCAtTHMgJ2h0dHA6Ly9hcGkuZ2l0aHViLmNvbS9yZXBvcy9jYWlkby9jYWlkby9yZWxlYXNlcy9sYXRlc3QnKSIKQk9EWT0iJChlY2hvICIke0xBVEVTVF9SRUxFQVNFfSIgfCBqcSAtcyAnLltdLmJvZHknKSIKTElOVVhfWDg2XzY0PSIkKGVjaG8gLWUgXCIke0JPRFl9XCIgfCBncmVwIC1vRSAnXi4rXFtMaW51eCB4ODZfNjRcXVwoLipcKScgfCBzZWQgJ3MvLiooXCguKlwpKS9cMS9nJykiCgpjdXJsIC1MICIke0xJTlVYX1g4Nl82NH0iIHwgdGFyIHp4ZiAtIC1DICIke0hPTUV9Ly5sb2NhbC9iaW4vIgoK' | base64 -d | bash"
    - name: Install tools using Cargo
      block:
        - name: Define CARGO_HOME
          set_fact:
            GOPATH: "{{ ansible_env.HOME }}/.local/share/cargo"
        - name: Install evtx (Windows Event Log parser)
          ansible.builtin.command:
            cmd: "cargo install evtx"
        - name: Install rustscan
          ansible.builtin.command:
            cmd: "cargo install rustscan"

