---
- name: Setup security tools
  hosts: localhost
  tasks:
    - name: Update repositories
      ansible.builtin.dnf:
        name: "*"
        update_cache: yes
        state: latest
      become: true
    - name: Install packages using dnf
      ansible.builtin.dnf:
        name:
          - aircrack-ng
          - binwalk
          - chisel
          - dnsenum
          - hashcat
          - hivex
          - hydra
          - medusa
          - nmap
          - onesixtyone
          - perl-HTML-Parser
          - perl-Net-DNS
          - perl-Net-IP
          - perl-Net-Netmask
          - perl-WWW-Mechanize
          - perl-XML-Writer
          - python3-argcomplete
          - python3-colorlog
          - python3-cx-oracle
          - python3-natlas-libnmap
          - python3-passlib
          - python3-pyasyncore
          - python3-pycryptodomex
          - python3-scapy
          - python3-scrapy
          - python3-termcolor
          - radare2
          - tcpdump
          - wafw00f
          - whois
          - wireshark
      become: true
    - name: Install tools using cargo
      block:
        - name: Define CARGO_HOME
          set_fact:
            GOPATH: "{{ ansible_env.HOME }}/.local/share/cargo"
        - name: Install evtx (Windows Event Log parser)
          ansible.builtin.command:
            cmd: "cargo install evtx"
        - name: Install rustscan
          ansible.builtin.command:
            cmd: "cargo install rustscan"
    - name: Install tools using gem
      block:
        - name: Install evil-winrm
          ansible.builtin.command:
            cmd: "gem install evil-winrm"
        - name: Install wpscan
          ansible.builtin.command:
            cmd: "gem install wpscan"
    - name: Install tools using go
      block:
        - name: Define GOPATH
          set_fact:
            GOPATH: "{{ ansible_env.HOME }}/.local/share/go"
        - name: Install ffuf
          ansible.builtin.command:
            cmd: "go install github.com/ffuf/ffuf/v2@latest"
        - name: Install httpx
          ansible.builtin.command:
            cmd: "go install github.com/projectdiscovery/httpx/cmd/httpx@latest" 
        - name: Install interactsh-client
          ansible.builtin.command:
            cmd: "go install github.com/projectdiscovery/interactsh/cmd/interactsh-client@latest"
        - name: Install kerbrute
          ansible.builtin.command:
            cmd: "go install github.com/ropnop/kerbrute@latest"
    - name: Install tools using pipx
      block:
        - name: Install bloodhound ingestor
          ansible.builtin.command:
            cmd: "pipx install bloodhound-ce"
        - name: Install certipy
          ansible.builtin.command:
            cmd: "pipx install certipy"
        - name: Install enum4linux-ng
          ansible.builtin.command:
            cmd: "pipx install git+https://github.com/cddmp/enum4linux-ng.git"
        - name: Install git-dumper
          ansible.builtin.command:
            cmd: "pipx install git-dumper"
        - name: Install impacket
          ansible.builtin.shell: |
            pipx install impacket
            pipx inject impacket pycryptodomex
        - name: Install NetExec
          ansible.builtin.command:
            cmd: "pipx install git+https://github.com/Pennyw0rth/NetExec.git"
        - name: Install pywhisker
          ansible.builtin.command:
            cmd: "pipx install git+https://github.com/ShutdownRepo/pywhisker.git"
        - name: Install regpol
          ansible.builtin.command:
            cmd: "pipx install git+https://github.com/jtpereyda/regpol.git"
        - name: Install smtp-user-enum
          ansible.builtin.command:
            cmd: "pipx install smtp-user-enum"
        - name: Install ssh-audit
          ansible.builtin.command:
            cmd: "pipx install ssh-audit"
    - name: Manually install tools
      block:
        - name: Install caido
          ansible.builtin.shell: | 
            LATEST_RELEASE="$(curl -Ls 'http://api.github.com/repos/caido/caido/releases/latest')"
            BODY="$(echo "${LATEST_RELEASE}" | jq -s '.[].body')"
            LINUX_X86_64="$(echo -e \"${BODY}\" | grep -oE '^.+\[Linux x86_64\]\(.*\)' | sed 's/.*(\(.*\))/\1/g')"
            curl -L "${LINUX_X86_64}" | tar zxf - -C "${HOME}/.local/bin/"
        - name: Install Oracle Instant Client
          become: true
          ansible.builtin.shell: |
            dnf install -y https://download.oracle.com/otn_software/linux/instantclient/oracle-instantclient-basic-linuxx64.rpm
            dnf install -y https://download.oracle.com/otn_software/linux/instantclient/oracle-instantclient-devel-linuxx64.rpm
            dnf install -y https://download.oracle.com/otn_software/linux/instantclient/oracle-instantclient-sqlplus-linuxx64.rpm
        - name: Install odat
          ansible.builtin.shell: |
            git clone https://github.com/quentinhardy/odat.git "${HOME}/.local/opt/odat"
            cd "${HOME}/.local/opt/odat"
            git submodule init
            git submodule update
